#############################################################################
#   $ make all         compile and link all programs
#   $ make clean       clean objects and the executable file
##==========================================================================
CC := javac

all: Simpella

Simpella : 
	${CC} *.java
	@- echo "Compiled Successfully!!!"
        

##==========================================================================
clean:
	@- $(RM) *.class
	@- $(RM) Files/*.txt
	@- echo "Data Cleansing Done.Ready to Compile"


